### ISSUE TITLE
i want to how to use this pro to gererate moire video 

### ISSUE THREAD

**Issue by zhanghongyong123456** [korkmazkadir/moire-pattern-video-exporter#1]
in  windows   , as a video as input

**Comment by korkmazkadir** [comment]
Hello,
Today, I have explained the details in README file.
(Check the main page of the project.)

I did not run it on windows. I have used Mac or Ubuntu, I believe it will be easier to run on Mac or Ubuntu because
the script files have not been tested on windows.

It creates a video that contains moire patter.
